proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;


server {
    listen 80;
    server_name demo.checkmate.so staging.checkmate.so;

    location /.well-known/acme-challenge/ {
        # Forward the challenge to Certbot listening on 8080
        proxy_pass http://172.17.0.1:8080;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


# --- DEMO: demo.checkmate.so ---
server {
    listen 443 ssl;
    server_name demo.checkmate.so;

    ssl_certificate     /etc/nginx/ssl/live/demo.checkmate.so/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/demo.checkmate.so/privkey.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        # The mono image serves both the SPA and the API
        proxy_pass http://checkmate-demo:52345;
    }
}

# --- STAGING: staging.checkmate.so ---
server {
    listen 443 ssl;
    server_name staging.checkmate.so;

    ssl_certificate     /etc/nginx/ssl/live/staging.checkmate.so/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/staging.checkmate.so/privkey.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        # The mono image serves both the SPA and the API
        proxy_pass http://checkmate-staging:52345;
    }
}
