{{- $api := include "checkmate.api" . | fromYaml -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmate-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmate-client
  template:
    metadata:
      labels:
        app: checkmate-client
    spec:
    {{- with .Values.client.affinity }}
      affinity:
        {{- tpl ( . | toYaml) $ | nindent 8 }}
    {{- end }}
    {{- with .Values.client.tolerations }}
      tolerations:
        {{- tpl ( . | toYaml) $ | nindent 8 }}
    {{- end }}
      containers:
        - name: client
          image: {{ include "checkmate.image" (dict "image" .Values.client.image "tag" .Values.client.tag "root" $) }}
          imagePullPolicy: {{ .Values.client.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.client.port }}
          env:
            - name: UPTIME_APP_API_BASE_URL
              value: "{{ $api.protocol }}://{{ $api.ingress.host }}/api/v1"
            - name: UPTIME_APP_CLIENT_HOST
              value: "{{ .Values.client.protocol }}://{{ .Values.client.ingress.host }}"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          {{- with .Values.client.resources }}
          resources:
              {{- tpl ( . | toYaml) $ | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: checkmate-client-nginx-cm
