{{- if .Values.client.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkmate-client-ingress
  {{- if .Values.client.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.client.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.client.ingress.className }}
  {{- if .Values.client.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.client.ingress.host }}
      secretName: {{ default (printf "%s-client-tls" .Release.Name) .Values.client.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.client.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checkmate-client
                port:
                  number: {{ .Values.client.port }}
{{- end }}
